# Generated by Django 5.1.6 on 2025-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leerkrachten',
            name='werkzaam_sinds',
            field=models.DateField(),
        ),
    ]
