# Generated by Django 5.1.6 on 2025-03-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0002_alter_leerkrachten_werkzaam_sinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='event',
            field=models.CharField(default='event', max_length=40),
            preserve_default=False,
        ),
    ]
