# Generated by Django 4.2.20 on 2025-04-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0003_stageopdrachtcalevents_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stageopdrachten',
            old_name='verwachte_attitudes',
            new_name='verwachtte_attitudes',
        ),
    ]
