# Generated by Django 4.2.20 on 2025-04-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0004_rename_verwachte_attitudes_stageopdrachten_verwachtte_attitudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageopdrachten',
            name='stage_opportuniteit',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stageopdrachten', to='stageapp.stageopportuniteiten', verbose_name='Kan referentie naar een stageopportuniteit bevatten. Indien niet, dan rechtstreeks aangemaakt.'),
        ),
    ]
