# Generated by Django 4.2.20 on 2025-04-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0006_alter_stageopdrachten_stage_opportuniteit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrijfsvestingen',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bedrijvengroep',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactpersonen',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leerkrachten',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scholen',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scholengroep',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studenten',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
