# Generated by Django 4.2.20 on 2025-04-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0007_alter_bedrijfsvestingen_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageopdrachten',
            name='datum_stage_opdracht_afgesloten',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
