# Generated by Django 4.2.20 on 2025-04-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0008_alter_stageopdrachten_datum_stage_opdracht_afgesloten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageopdrachten',
            name='actief',
            field=models.BooleanField(default=False, help_text='Aangevinkt indien opdracht actief is.'),
        ),
        migrations.AlterField(
            model_name='stageopdrachten',
            name='afspraken',
            field=models.TextField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachten',
            name='datum_stage_opdracht_afgesloten',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum afgesloten'),
        ),
        migrations.AlterField(
            model_name='stageopdrachten',
            name='last_updated_by',
            field=models.CharField(blank=True, default='Admin', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachten',
            name='stage_opdracht_afgesloten',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stageopdrachten',
            name='stage_opportuniteit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stageopdrachten', to='stageapp.stageopportuniteiten', verbose_name='Referentie naar een stageopportuniteit indien van toepassing'),
        ),
        migrations.AlterField(
            model_name='stageopdrachten',
            name='verwachtte_attitudes',
            field=models.TextField(blank=True, default=False, null=True),
        ),
    ]
