# Generated by Django 4.2.20 on 2025-04-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0009_alter_stageopdrachten_actief_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalEventTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('H', 'Herinnering'), ('A', 'Afspraak'), ('T', 'Taak')], default='T', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='taaktype',
            name='taak_type',
            field=models.CharField(max_length=255, verbose_name='activiteit, tussentijdsverslag, eindverslag, tussenevaluatie, ...'),
        ),
        migrations.AlterField(
            model_name='taken',
            name='datum_ingediend',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taken',
            name='datum_nagekeken',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taken',
            name='feedback_door',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user id van de persoon die de taak heeft nagekeken en feedback ingevuld.'),
        ),
        migrations.AlterField(
            model_name='taken',
            name='ingeschatte_effort_hrs',
            field=models.FloatField(blank=True, null=True, verbose_name='Ingeschatte effort in uren'),
        ),
        migrations.AlterField(
            model_name='taken',
            name='nagekeken',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='stagebegeleider kan aangeven of taak nagekeken is.  Feedback daarna ook zichtbaar voor student.'),
        ),
        migrations.AlterField(
            model_name='taken',
            name='progressie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingeschatte progressie in %'),
        ),
        migrations.AlterField(
            model_name='taken',
            name='taak_bijlage',
            field=models.FileField(blank=True, null=True, upload_to='taken/'),
        ),
        migrations.AlterField(
            model_name='taken',
            name='taak_feedback',
            field=models.TextField(blank=True, default=False, null=True, verbose_name='feedback stagebegeleider op ingediende/afgewerkte taak'),
        ),
        migrations.AlterField(
            model_name='taken',
            name='taak_ingediend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aangevinkt = student heeft taak afgewerkt en ingediend'),
        ),
        migrations.AlterField(
            model_name='taken',
            name='taak_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taken',
            name='taak_zelfevalutie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taken',
            name='werkelijke_effort_hrs',
            field=models.FloatField(blank=True, null=True, verbose_name='Werkelijk benodigd aantal uren om taak af te werken/uit te voeren.'),
        ),
        migrations.AlterField(
            model_name='stageopdrachtcalevents',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stageopdrachtcalevents', to='stageapp.caleventtypes'),
        ),
    ]
