# Generated by Django 4.2.20 on 2025-04-17 18:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0010_caleventtypes_alter_taaktype_taak_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageopdrachtevaluatiedetails',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='stageopdrachtevaluatiedetails',
            name='EvaluatieTemplateHoofddeel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stageopdrachtevaluatiedetails', to='stageapp.evaluatietemplatehoofddeel'),
        ),
        migrations.AlterField(
            model_name='stageopdrachtevaluatiedetails',
            name='EvaluatieTemplateSubdeel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stageopdrachtevaluatiedetails', to='stageapp.evaluatietemplatesubdeel'),
        ),
        migrations.AlterField(
            model_name='stageopdrachtevaluaties',
            name='datum_last_update_notities_studentverantwoordelijke',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachtevaluaties',
            name='datum_ontvangst_studentverantwoordelijke',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachtevaluaties',
            name='datum_vrijgegeven',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachtevaluaties',
            name='notities_studentverantwoordelijke',
            field=models.TextField(blank=True, null=True),
        ),
    ]
