# Generated by Django 4.2.20 on 2025-04-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0011_stageopdrachtevaluatiedetails_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afdelingen',
            name='bedrijvengroep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='afdelingen', to='stageapp.bedrijvengroep'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stageopdrachtevaluaties',
            name='stageopdrachten',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stageopdrachtevaluaties', to='stageapp.stageopdrachten'),
        ),
    ]
