# Generated by Django 4.2.20 on 2025-04-20 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0012_afdelingen_bedrijvengroep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrijvengroep',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bedrijvengroep',
            name='website',
            field=models.TextField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
