# Generated by Django 4.2.20 on 2025-04-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0013_alter_bedrijvengroep_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedrijfsvestingen',
            name='bedrijvengroep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedrijfsvestingen', to='stageapp.bedrijvengroep'),
        ),
    ]
