# Generated by Django 4.2.20 on 2025-05-27 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0014_alter_bedrijfsvestingen_bedrijvengroep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afdelingen',
            name='afdeling_omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bedrijfsvestingen',
            name='website',
            field=models.TextField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='stageopdrachten',
            name='afspraken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachten',
            name='verwachtte_attitudes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachtevaluatiedetails',
            name='score_argumentatie',
            field=models.TextField(blank=True, null=True, verbose_name='bijkomende argumentatie bij quantitatieve score'),
        ),
        migrations.AlterField(
            model_name='stageopdrachtevaluatiedetails',
            name='score_nvt',
            field=models.BooleanField(default=False, verbose_name='Aangevinkt als score niet gegeven kan worden.'),
        ),
        migrations.AlterField(
            model_name='stageopdrachtevaluatiedetails',
            name='score_opmerking',
            field=models.TextField(blank=True, null=True, verbose_name='When type = 2; vrij tekst opmerking/feedback voor qualitatieve assessment.'),
        ),
    ]
