# Generated by Django 4.2.20 on 2025-05-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0015_alter_afdelingen_afdeling_omschrijving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenten',
            name='klassen',
            field=models.ManyToManyField(related_name='member_of_klas', to='stageapp.klassen'),
        ),
    ]
