# Generated by Django 4.2.20 on 2025-06-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0016_alter_studenten_klassen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageopdrachtevaluatiedetails',
            name='score_nvt',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aangevinkt als score niet gegeven kan worden.'),
        ),
        migrations.AlterField(
            model_name='studenten',
            name='klassen',
            field=models.ManyToManyField(related_name='klassen', to='stageapp.klassen'),
        ),
    ]
