# Generated by Django 4.2.20 on 2025-06-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0017_alter_stageopdrachtevaluatiedetails_score_nvt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatiescorerange',
            name='score_tot',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score tot: When type = 1; eg 10'),
        ),
        migrations.AlterField(
            model_name='evaluatiescorerange',
            name='score_van',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score van: When type = 1; eg 1'),
        ),
        migrations.AlterField(
            model_name='evaluatiescorerange',
            name='toelichting_score_range',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachtevaluatiedetails',
            name='score_nvt',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='NVT: Als score niet gegeven kan worden.'),
        ),
        migrations.AlterField(
            model_name='stageopdrachtevaluatiedetails',
            name='score_opmerking',
            field=models.TextField(blank=True, null=True, verbose_name='Vrije feedback voor qualitatieve assessment.'),
        ),
    ]
