# Generated by Django 4.2.20 on 2025-06-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0018_alter_evaluatiescorerange_score_tot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageopdrachtcalevents',
            name='type',
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='event_type',
            field=models.CharField(choices=[('H', 'Herinnering'), ('A', 'Afspraak'), ('T', 'Taak')], default='T', max_length=1),
        ),
    ]
