# Generated by Django 4.2.20 on 2025-06-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0019_remove_stageopdrachtcalevents_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalEventTypes',
        ),
    ]
