# Generated by Django 4.2.20 on 2025-06-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0020_delete_caleventtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='afspraak_invitees',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='afspraak sturen naar x emails'),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
    ]
