# Generated by Django 4.2.20 on 2025-06-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0021_stageopdrachtcalevents_afspraak_invitees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageopdrachtcalevents',
            name='event_type',
            field=models.CharField(choices=[('Herinnering', 'Herinnering'), ('Afspraak', 'Afspraak'), ('Taak', 'Taak')], default='Taak', max_length=40),
        ),
        migrations.AlterField(
            model_name='taken',
            name='stageopdrachtcalevents',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taken', to='stageapp.stageopdrachtcalevents'),
        ),
        migrations.AlterField(
            model_name='taken',
            name='taak_omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
    ]
