# Generated by Django 4.2.20 on 2025-06-08 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0022_alter_stageopdrachtcalevents_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='datum_ingediend',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='datum_nagekeken',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='feedback_door',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user id van de persoon die de taak heeft nagekeken en feedback ingevuld.'),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='ingeschatte_effort_hrs',
            field=models.FloatField(blank=True, null=True, verbose_name='Ingeschatte effort in uren'),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='nagekeken',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='stagebegeleider kan aangeven of taak nagekeken is.  Feedback daarna ook zichtbaar voor student.'),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='progressie',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingeschatte progressie in %'),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='taak',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='taak_bijlage',
            field=models.FileField(blank=True, null=True, upload_to='taken/'),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='taak_feedback',
            field=models.TextField(blank=True, default=False, null=True, verbose_name='feedback stagebegeleider op ingediende/afgewerkte taak'),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='taak_ingediend',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aangevinkt = student heeft taak afgewerkt en ingediend'),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='taak_omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='taak_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='taak_zelfevalutie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='taaktype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taaktype', to='stageapp.taaktype'),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='werkelijke_effort_hrs',
            field=models.FloatField(blank=True, null=True, verbose_name='Werkelijk benodigd aantal uren om taak af te werken/uit te voeren.'),
        ),
    ]
