# Generated by Django 4.2.20 on 2025-06-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0023_stageopdrachtcalevents_datum_ingediend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageopdrachtcalevents',
            name='nagekeken',
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='taak_nagekeken',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachtcalevents',
            name='feedback_door',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachtcalevents',
            name='taak_feedback',
            field=models.TextField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachtcalevents',
            name='taak_ingediend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachtcalevents',
            name='werkelijke_effort_hrs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
