# Generated by Django 4.2.20 on 2025-06-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0024_remove_stageopdrachtcalevents_nagekeken_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stageopdrachtcalevents',
            old_name='taak_zelfevalutie',
            new_name='taak_zelfevaluatie',
        ),
    ]
