# Generated by Django 4.2.20 on 2025-06-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0025_rename_taak_zelfevalutie_stageopdrachtcalevents_taak_zelfevaluatie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taaktype',
            name='taak_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='taaktype',
            name='taak_type_omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
    ]
