# Generated by Django 4.2.20 on 2025-06-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0026_alter_taaktype_taak_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stageopdrachtcalevents',
            old_name='werkelijke_effort_hrs',
            new_name='actual_effort_hrs',
        ),
        migrations.RemoveField(
            model_name='stageopdrachtcalevents',
            name='ingeschatte_effort_hrs',
        ),
        migrations.RemoveField(
            model_name='stageopdrachtcalevents',
            name='progressie',
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='estimate_effort_hrs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stageopdrachtcalevents',
            name='wip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
