# Generated by Django 4.2.20 on 2025-06-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0027_rename_werkelijke_effort_hrs_stageopdrachtcalevents_actual_effort_hrs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageopdrachtcalevents',
            name='afspraak_invitees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachtcalevents',
            name='event_tot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachtcalevents',
            name='taak_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stageopdrachtcalevents',
            name='taaktype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taaktype', to='stageapp.taaktype'),
        ),
    ]
