# Generated by Django 4.2.20 on 2025-06-11 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stageapp', '0028_alter_stageopdrachtcalevents_afspraak_invitees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leerkrachten',
            name='scholen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scholen', to='stageapp.scholen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenten',
            name='scholen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='studenten', to='stageapp.scholen'),
            preserve_default=False,
        ),
    ]
